version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: sekchat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    # Tüm IP'lerden bağlantıya izin ver

  backend:
    build:
      context: ./backend
    container_name: sekchat-backend-container
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_DATABASE: sekchat
      PG_USER: postgres
      PG_PASSWORD: 1q2w3e4r
      PORT: 5001
      JWT_SECRET: secretsformyapp
      NODE_ENV: development
      CLOUDINARY_CLOUD_NAME: dybzguiwh
      CLOUDINARY_API_KEY: 256415445651946
      CLOUDINARY_API_SECRET: Jwxx1esdPl8FQf3uomkyfwIvvfE

volumes:
  postgres_data:
